---
title: "Textbooks"
author: "Cassie Malcom"
date: "2/17/2022"
output: 
  html_document:
        toc: true
        toc_float: true
        toc_depth: 4
        highlight: kate
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library-install, echo=FALSE}
library(pacman)
# install.packages(arrow)
```

```{r load-pkgs, echo=FALSE}
pacman::p_load(edld652, tidyverse, psych, rio, here, forcats, arrow, dplyr, stringr, readr, tidyr)
```

```{r calldata, echo=FALSE, eval=FALSE, results='hide'}
ethnic <- get_data("NCES_CCD_nonfiscal_school_2019_membership")

ethnic
```

```{r ethnic2, echo=FALSE, eval=FALSE, results='hide'}
e2 <- ethnic %>%
  filter(!is.na(STUDENT_COUNT))

e2
```

```{r ethnic3, echo=FALSE, eval=FALSE, results='hide'}
e3 <- e2 %>%
  filter((GRADE=="Grade 9")|(GRADE=="Grade 10")|(GRADE=="Grade 11")|(GRADE=="Grade 12")|(str_detect(SCH_NAME, "High")))

e3
```

```{r checknames, echo=FALSE, eval=FALSE, results='hide'}
colnames(e3)
```

```{r ehtnic4, echo=FALSE, eval=FALSE, results='hide'}
e4 <- e3 %>%
  select(LEAID, GRADE, SCH_NAME, SCHOOL_YEAR, RACE_ETHNICITY, SEX, STUDENT_COUNT, ST)

e4
```

```{r ethnic5, echo=FALSE, eval=FALSE, results='hide'}
e5 <- e4 %>%
  group_by(ST, LEAID, RACE_ETHNICITY) %>%
  summarize(student = sum(STUDENT_COUNT))

e5
```
Filter out the "no category codes" and "not specified", "two or more races"
```{r ethnic6, echo=FALSE, eval=FALSE, results='hide'}
e6 <- e5 %>%
  filter(RACE_ETHNICITY!="Not Specified" & RACE_ETHNICITY!="No Category Codes" & RACE_ETHNICITY!="Two or more races")

e6
```

```{r savec, echo=FALSE, eval=FALSE, results='hide'}
write.csv(e6, "ethnicity2.csv")
```

```{r calldata2, echo=FALSE, results='hide'}
ed <- read.csv("/Users/cassiemalcom/Desktop/CM2020/22_Winter Term Classes/EDLD 652_DS2/EDLD652_FinalPrj/Data/ethnicity2.csv")

ed
```

```{r ethnicdata2, echo=FALSE, results='hide'}
ed2 <- ed %>%
  select(c(2,3,4))

ed2
```

```{r ethnicdata3, echo=FALSE, results='hide'}
ed3 <- ed2 %>%
  group_by(LEAID) %>%
  mutate(total = sum(student))

ed3
```

Need to get all minorities into one sum. Pivot?
```{r ethnicdata3, echo=FALSE, results='hide'}
ed4 <- ed3 %>%
  pivot_wider(names_from = RACE_ETHNICITY, values_from = student)

ed4
```

How to get a table like this to scroll on knitting to HTML?
```{r minorities}
ed4$minority <- rowSums(ed4[ , c(3,4,5,6,7)], na.rm=TRUE)

ed4
```

```{r}
ed5 <- ed4 %>%
  mutate(percentW = round(White/total*100, digits = 2), percentM = round(minority/total*100, digits = 2))

ed5
```

```{r}

```

